import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import LoginHeader from '../../../../../../src/core/pages/login/components/header'
import React from 'react'
// Generated by CodiumAI

describe('LoginHeader', () => {
  it('renders login header with correct title and description', () => {
    render(<LoginHeader />)

    const titleElement = screen.getByText('Pagos PSE de DING')
    const descriptionElement = screen.getByText(
      'Por favor ingresa tu número de celular y la clave con la que normalmente ingresas a DING.'
    )

    expect(titleElement).toBeDefined()
    expect(descriptionElement).toBeDefined()
  })

  it('renders login header with correct typography variant and size', () => {
    render(<LoginHeader />)

    const titleElement = screen.getByText('Pagos PSE de DING')
    const descriptionElement = screen.getByText(
      'Por favor ingresa tu número de celular y la clave con la que normalmente ingresas a DING.'
    )

    expect(titleElement).toBeDefined()
    expect(descriptionElement).toBeDefined()
  })
})
